### ISSUE TITLE
Update LCA version and change outputs 

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/cecdss#82]
Update LCA to version 1.1.0, and then:

Changes: Can you delete the entries of NH3, SO2, and VOCs on the front end? Also, change the  unit of CO from kg to g and the unit of carbon intensity from g to kg. And change the entries in the exported csv files accordingly.

![image](https://user-images.githubusercontent.com/202753/117853121-e3872980-b23c-11eb-9376-3068407bcbdc.png)

**Comment by kaiyanl** [comment]
The table of individual years needs to be updated too

**Comment by srkirkland** [comment]
@wongband Basically we want the individual years "Lifecycle Analysis Results" to match the one under "All Results" for that specific year.  You'll see currently different compounds are displayed and some are missing on the individual pages.
